CLI: Implements workflow unassign/delete and other minor fixes
fuseml/fuseml-core pull request #69
Opened 2021-06-01 15:40 UTC by flaviodsr

- API: change workflow register to workflow create
- fix: when creating a webhook if it already exists return its ID instead of nil
- CLI: fix the order of codeset name and project parameters to be the same for all commands that needs it
- CLI: Implements the workflow unassign and delete commands.

2021-06-01 18:46 UTC, stefannica requested changes

2021-06-01 18:46 UTC, stefannica commented on design/workflow.go
>  			Response(StatusNoContent)
Hehe, I reckon you did all this just so you would have the payload builder arguments generated in the right order :))) I appreciate the attention to detail.

2021-06-01 18:46 UTC, stefannica commented on pkg/cli/workflow/unassign.go
> +		Long:  `Removes the assingment between a workflow and a codeset.`,
typo: assingment

2021-06-01 18:46 UTC, stefannica commented on pkg/cli/workflow/unassign.go
> +	cmd.Flags().StringVarP(&o.name, "name", "n", "", "name of the workflow to be unassigned")
nit: it's the codeset that is unassigned from a workflow, not the other way around, isn't it ? `workflow name` is probably enough here

2021-06-02 09:07 UTC, stefannica approved these changes

2021-06-02 09:19 UTC, jsuchome approved these changes

2021-06-02 13:34 UTC, merged